name: Build Multi-Platform Binaries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Build Binary
        run: |
          export GOOS=${{ matrix.os }}
          export GOARCH=${{ matrix.arch }}
          export OUTPUT_FILE="3x-ui-traffic-exporter-${GOOS}-${GOARCH}${{ matrix.os == 'windows' && '.exe' || '' }}"
          echo "Building for ${GOOS}/${GOARCH}..."
          go build -o $OUTPUT_FILE main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 3x-ui-traffic-exporter-${{ matrix.os }}-${{ matrix.arch }}
          path: 3x-ui-traffic-exporter-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}
